// Airlines serving Saudi Arabia / Pakistan routes plus major global carriers.
// Used by the ticket form's searchable airline picker.
export const airlines: string[] = [
  "PIA",
  "Airblue",
  "SereneAir",
  "AirSial",
  "Fly Jinnah",
  "Saudia",
  "flynas",
  "flyadeal",
  "Emirates",
  "Etihad Airways",
  "Qatar Airways",
  "flydubai",
  "Air Arabia",
  "Gulf Air",
  "Oman Air",
  "SalamAir",
  "Kuwait Airways",
  "Jazeera Airways",
  "Turkish Airlines",
  "Pegasus Airlines",
  "Egyptair",
  "Royal Jordanian",
  "Middle East Airlines",
  "Iraqi Airways",
  "Yemenia",
  "Azerbaijan Airlines",
  "Mahan Air",
  "Iran Air",
  "Uzbekistan Airways",
  "Ethiopian Airlines",
  "Kenya Airways",
  "Biman Bangladesh Airlines",
  "SriLankan Airlines",
  "IndiGo",
  "Air India",
  "Malaysia Airlines",
  "Thai Airways",
  "Singapore Airlines",
  "Cathay Pacific",
  "China Southern Airlines",
  "British Airways",
  "Virgin Atlantic",
  "Lufthansa",
  "KLM",
  "Air France",
  "Swiss",
  "Aeroflot",
];
